// 高志凯核心论点预置监控项（AI 填实时读数）。lastReading 首次采集前为 null。
export const presets = [
  {
    id: 'us-debt',
    title: '美国国债与利息支出',
    searchQuery: '美国国债总额最新数据、年度利息支出、利息占财政收入比例、是否超过国防开支',
    impactRule: '国债规模与利息支出越高、占财政比例越大、临近债务上限或评级下调风险越高，则美股系统性风险越高。',
    weight: 20,
    direction: 'increase',
    lastReading: null,
  },
  {
    id: 'fed-rates',
    title: '美联储利率与降息路径',
    searchQuery: '美联储最新联邦基金利率、最近一次议息会议表态、市场对降息/加息预期、点阵图',
    impactRule: '利率维持高位、降息预期落空或重新加息，会抬高融资成本、压制估值，推高崩盘概率；明确降息则降低。',
    weight: 15,
    direction: 'increase',
    lastReading: null,
  },
  {
    id: 'de-dollarization',
    title: '去美元化与美元信用',
    searchQuery: '去美元化最新进展、金砖国家本币结算、各国美元储备占比变化、美元指数走势',
    impactRule: '去美元化加速、美元储备地位下降、美元信用受质疑，会削弱美股长期资金基础，推高风险。',
    weight: 15,
    direction: 'increase',
    lastReading: null,
  },
  {
    id: 'ai-bubble',
    title: 'AI 科技股泡沫与估值集中度',
    searchQuery: '美股 Magnificent 7 估值、标普500 席勒市盈率 CAPE、AI 板块估值是否泡沫、市值集中度',
    impactRule: '估值越高、市值越集中于少数 AI 科技股、泡沫迹象越明显，一旦回调引发系统性下跌的概率越高。',
    weight: 20,
    direction: 'increase',
    lastReading: null,
  },
  {
    id: 'cre-banks',
    title: '美国商业地产与区域银行风险',
    searchQuery: '美国商业地产空置率与违约、区域银行存款与坏账、银行业流动性压力最新情况',
    impactRule: '商业地产违约上升、区域银行暴露风险、流动性紧张，可能引发信用事件并传导至股市。',
    weight: 15,
    direction: 'increase',
    lastReading: null,
  },
  {
    id: 'geopolitics',
    title: '地缘政治冲突（台海/中东/贸易战）',
    searchQuery: '台海局势、中东冲突、中美贸易战与关税最新进展，对市场风险偏好的影响',
    impactRule: '地缘冲突升级、关税与贸易摩擦加剧，会打击风险偏好、扰乱供应链，推高崩盘概率。',
    weight: 15,
    direction: 'increase',
    lastReading: null,
  },
]
