import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const files = [
  ['index.html', 'text/html; charset=utf-8'],
  ['style.css', 'text/css; charset=utf-8'],
  ['app.js', 'application/javascript; charset=utf-8'],
]

const entries = files.map(([name, type]) => {
  const body = readFileSync(join(root, 'public', name), 'utf8')
  return `  ${JSON.stringify(name)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(body)} }`
})

const out = `// AUTO-GENERATED by scripts/embed-assets.mjs — 请勿手改\nexport const ASSETS = {\n${entries.join(',\n')}\n}\n`
writeFileSync(join(root, 'server', 'assets.generated.js'), out, 'utf8')
console.log(`embedded ${files.length} assets → server/assets.generated.js`)
